### ISSUE TITLE
Add support for Data Tiering

### ISSUE THREAD

**Issue by monrax** [Graylog2/graylog-helm#9]
Datanode should support Data Tiering. The required values are detailed here: https://go2docs.graylog.org/current/setting_up_graylog/data_node_configuration_file.htm#s3

i.e. `path_repo`, as well as all `s3_*` parameters.

**Comment by monrax** [comment]
### Update

## TL; DR
- S3 data tiering is implemented and validated against both AWS S3 and a live MinIO cluster.
- The only remaining gap is `path_repo`.
- Considering the runtime environment is Kubernetes, using a MinIO chart (or any other S3-compatible object store alternatives) is preferred.
- Actual AWS S3 storage also works fine in cases where remote access to AWS from the org is allowed.

## Validation

The S3 side of this request is fully implemented in the current chart in `charts/graylog/`. In its values, `datanode.config` exposes `nodeSearchCacheSize` and the full `s3ClientDefault*` set (endpoint, region, protocol, pathStyleAccess, accessKey, secretKey), which map 1:1 to the Data Node's `S3RepositoryConfiguration` / `Configuration`.

This was validated end-to-end on EKS with an Enterprise license against two object store backends:

- **AWS S3**: with `s3ClientDefaultProtocol: https` and `s3ClientDefaultPathStyleAccess: false`
- In-cluster **MinIO**: with the chart defaults `http` + `path_style_access: true`

In both cases the full lifecycle worked:
- warm-tier repository verified against the bucket (`ready: true`)
- 200 ingested messages snapshotted on rotation (`snapshot ... completed with state [SUCCESS]`)
- mounted as a searchable-snapshot `*_warm_*` index with data still searchable
- real snapshot objects confirmed present in the bucket.

## Remaining gap: `path_repo`

The filesystem/shared-volume searchable-snapshot backend is not implemented. #19 started this with the following values block:

```yaml
      warmTier:
        enabled: false
        storageClass: ""
        existingClaim: ""
        mountPath: ""
        accessModes: []
        size: "8Gi"
        annotations: {}
        labels: {}
        selector: {}
        dataSource: {}
```

But it wasn't followed with any `path_repo` wiring.

We're closing this issue as done for S3 Data Tiering, as well as the stale PR. We'll be tracking `path_repo` support separately.
